[package]
name = "webx"
version = "0.1.0"
edition = "2021"
description = "A comprehensive backend web framework."
authors = ["William Ragstad"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.3.21"
colored = "2.0.4"
