[package]
name = "webx"
version = "0.1.0"
edition = "2021"
description = "A DSL and framework for building backend web servers."
authors = ["William Rågstad"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.21", features = ["color"] }
colored = "2.0.4"
serde = { version = "1.0.183", features = ["derive"]}
serde_json = "1.0.104"
